### ISSUE TITLE
Nil error Molten Core

### ISSUE THREAD

**Issue by Aviana** [EsreverWoW/LibThreatClassic#8]
12x ...BM-Core\Libs\ThreatClassic-1.0\ThreatClassic-1.0-4.lua:391: bad argument #2 to 'strsplit' (string expected, got nil)
[C]: ?
...BM-Core\Libs\ThreatClassic-1.0\ThreatClassic-1.0-4.lua:391: in function `NPCID'
...-Core\Libs\ThreatClassic-1.0-4\ThreatNPCModuleCore.lua:459: in function `?'
...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:119: in function <...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `Fire'
...dOns\Broker_uClock\Lib\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <...dOns\Broker_uClock\Lib\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals:
InCombatSkipped

**Comment by EsreverWoW** [comment]
Firstly, you are running an out of date copy of DBM which has an old version of this library. Updating DBM at this point won't fix it, since the latest copy was release prior to the fix two days ago in f0f994eb36bf3dc7848d043e6b546984c1f5e50c, but LibThreatClassic is in the pkgmeta for DBM and will get updated on next release. If you choose, you can manually update the embedded lib yourself in the meantime.

**Comment by cannonpalms** [comment]
Issue migrated to cannonpalms/LibThreatClassic#11
